name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: WordPress Plugin Check
      uses: wordpress/plugin-check-action@v1